package com.internhiring.backend.entity;

public enum AuditAction {
    USER_ROLE_UPDATED,
    USER_RESTRICTION_UPDATED,
    ADMIN_JOB_CREATED,
    ADMIN_JOB_TRASHED,
    ADMIN_JOB_RESTORED,
    ADMIN_JOB_DELETED,
    JOB_APPROVED,
    JOB_REJECTED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    RECRUITER_APPLICATION_APPROVED,
    RECRUITER_APPLICATION_REJECTED,
    RECRUITER_FORM_FIELD_CREATED,
    RECRUITER_FORM_FIELD_UPDATED,
    RECRUITER_FORM_FIELD_DELETED
}
