import {defineField, defineType} from 'sanity'
import {ColorInput} from './ColorInput'

const colorField = (
  name: string,
  title: string,
  initialValue: string,
  hidden?: (props: {document?: Record<string, unknown> | null}) => boolean,
) =>
  defineField({
    name,
    title,
    type: 'string',
    initialValue,
    ...(hidden ? {hidden} : {}),
    components: {
      input: ColorInput,
    },
    validation: (rule) =>
      rule.regex(/^#[0-9a-fA-F]{6}$/, {
        name: 'hex color',
        invert: false,
      }),
  })

const localizedTextFields = (
  name: string,
  title: string,
  type: 'string' | 'text' = 'string',
  rows?: number,
  hidden?: (props: {document?: Record<string, unknown> | null}) => boolean,
) => [
  defineField({
    name,
    title: `${title} (Default)`,
    type,
    ...(hidden ? {hidden} : {}),
    ...(rows ? {rows} : {}),
  }),
  defineField({
    name: `${name}Vi`,
    title: `${title} VI`,
    type,
    ...(hidden ? {hidden} : {}),
    ...(rows ? {rows} : {}),
  }),
  defineField({
    name: `${name}En`,
    title: `${title} EN`,
    type,
    ...(hidden ? {hidden} : {}),
    ...(rows ? {rows} : {}),
  }),
]

const isHomePageDocument = (document?: Record<string, unknown> | null) => document?.routePath === '/'

const defaultNavbarItems = [
  {
    _type: 'object',
    _key: 'about',
    isVisible: true,
    label: 'Giới thiệu',
    labelVi: 'Giới thiệu',
    labelEn: 'About',
    targetId: 'gioi-thieu',
  },
  {
    _type: 'object',
    _key: 'featured-jobs',
    isVisible: true,
    label: 'Việc làm nổi bật',
    labelVi: 'Việc làm nổi bật',
    labelEn: 'Featured jobs',
    targetId: 'viec-lam-noi-bat',
  },
  {
    _type: 'object',
    _key: 'partners',
    isVisible: true,
    label: 'Đối tác',
    labelVi: 'Đối tác',
    labelEn: 'Partners',
    targetId: 'doi-tac',
  },
  {
    _type: 'object',
    _key: 'recruitment',
    isVisible: true,
    label: 'Tuyển dụng',
    labelVi: 'Tuyển dụng',
    labelEn: 'Recruitment',
    targetId: 'tuyen-dung',
  },
]

export const managedPage = defineType({
  name: 'managedPage',
  title: 'Page Manager',
  type: 'document',
  groups: [
    {name: 'content', title: 'Default Page Content', hidden: ({document}) => isHomePageDocument(document)},
    {name: 'sections', title: 'Page Dynamic Sections', default: true},
    {name: 'style', title: 'Page Style', hidden: ({document}) => isHomePageDocument(document)},
    {name: 'home', title: 'Home Page Sections', hidden: ({document}) => !isHomePageDocument(document)},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Page Name',
      type: 'string',
      hidden: ({document}) => isHomePageDocument(document),
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'routePath',
      title: 'Page Route Path',
      type: 'string',
      hidden: ({document}) => isHomePageDocument(document),
      description: 'Used by the frontend to fetch static text translations and custom dynamic sections.',
      initialValue: '/',
      options: {
        list: [
          {title: 'Home Page', value: '/'},
          {title: 'Jobs Page', value: '/jobs'},
          {title: 'Job Detail Page', value: '/jobs/:jobId'},
          {title: 'Applications Page', value: '/applications'},
          {title: 'Profile Page', value: '/profile'},
          {title: 'Recruiter Verification Page', value: '/recruiter-verification'},
          {title: 'Company Profile Page', value: '/companies/:companyId'},
          {title: 'Reset Password Page', value: '/reset-password'},
          {title: 'Admin Dashboard', value: '/admin'},
          {title: 'Admin User Profile Page', value: '/admin/users/:userId'},
          {title: 'Admin Company Review Page', value: '/admin/company-reviews/:applicationId'},
          {title: 'Recruiter Dashboard', value: '/recruiter'},
          {title: 'Moderator Dashboard', value: '/moderator'},
        ],
      },
      validation: (rule) =>
        rule
          .required()
          .custom((value) =>
            value === '/login' || value === '/register'
              ? 'Login and Register pages are managed via dedicated schemas in Sanity.'
              : true,
          ),
    }),
    defineField({
      name: 'texts',
      title: 'Default Page Interface Text',
      type: 'array',
      hidden: () => true,
      description: 'Allows overriding static labels and default content mapped on the frontend.',
      group: 'content',
      of: [{type: 'managedInterfaceText'}],
    }),
    defineField({name: 'jobsContent', title: 'Default Content — Jobs Page', type: 'jobsPageContent', hidden: ({document}) => document?.routePath !== '/jobs', group: 'content'}),
    defineField({name: 'applicationsContent', title: 'Default Content — Applications Page', type: 'applicationsPageContent', hidden: ({document}) => document?.routePath !== '/applications', group: 'content'}),
    defineField({name: 'verificationContent', title: 'Default Content — Verification Page', type: 'verificationPageContent', hidden: ({document}) => document?.routePath !== '/recruiter-verification', group: 'content'}),
    defineField({name: 'adminContent', title: 'Default Content — Admin Dashboard', type: 'adminPageContent', hidden: ({document}) => document?.routePath !== '/admin', group: 'content'}),
    defineField({name: 'recruiterContent', title: 'Default Content — Recruiter Dashboard', type: 'recruiterPageContent', hidden: ({document}) => document?.routePath !== '/recruiter', group: 'content'}),
    defineField({name: 'moderatorContent', title: 'Default Content — Moderator Dashboard', type: 'moderatorPageContent', hidden: ({document}) => document?.routePath !== '/moderator', group: 'content'}),
    defineField({
      name: 'profileDefaults',
      title: 'Default Layout — Profile Page',
      type: 'object',
      hidden: ({document}) => document?.routePath !== '/profile',
      group: 'content',
      description: 'Allows customization of static fields and sections inside the candidate profile page.',
      fieldsets: [
        {name: 'personal', title: 'Personal Info Fields', options: {columns: 2}},
        {name: 'cv', title: 'CV Upload & Lists Fields', options: {columns: 2}},
        {name: 'company', title: 'Company Information Fields', options: {columns: 2}},
        {name: 'password', title: 'Change Password Form Fields', options: {columns: 2}},
        {name: 'style', title: 'Profile Page Accent Colors', options: {columns: 2}},
      ],
      fields: [
        defineField({
          name: 'isVisible',
          title: 'Enable Layout Settings',
          type: 'boolean',
          initialValue: true,
          description: 'Toggle off to revert profile page translations to frontend defaults.',
        }),
        defineField({name: 'editButton', title: 'Edit Button Label', type: 'string', fieldset: 'personal', placeholder: 'Chỉnh sửa'}),
        defineField({name: 'cancelButton', title: 'Cancel Button Label', type: 'string', fieldset: 'personal', placeholder: 'Hủy'}),
        defineField({name: 'saveButton', title: 'Save Button Label', type: 'string', fieldset: 'personal', placeholder: 'Lưu'}),
        defineField({name: 'lastNameLabel', title: 'Last Name Label', type: 'string', fieldset: 'personal', placeholder: 'Họ'}),
        defineField({name: 'firstNameLabel', title: 'First Name Label', type: 'string', fieldset: 'personal', placeholder: 'Tên'}),
        defineField({name: 'phoneLabel', title: 'Phone Number Label', type: 'string', fieldset: 'personal', placeholder: 'Số điện thoại'}),
        defineField({name: 'dobLabel', title: 'Date of Birth Label', type: 'string', fieldset: 'personal', placeholder: 'Ngày sinh'}),
        defineField({name: 'genderLabel', title: 'Gender Selection Label', type: 'string', fieldset: 'personal', placeholder: 'Giới tính'}),
        defineField({name: 'emailLabel', title: 'Email Address Label', type: 'string', fieldset: 'personal', placeholder: 'Email'}),
        defineField({name: 'selectPlaceholder', title: 'Dropdown Select Placeholder', type: 'string', fieldset: 'personal', placeholder: 'Chọn'}),
        defineField({name: 'lastNamePlaceholder', title: 'Last Name Input Placeholder', type: 'string', fieldset: 'personal', placeholder: 'Nhập họ'}),
        defineField({name: 'firstNamePlaceholder', title: 'First Name Input Placeholder', type: 'string', fieldset: 'personal', placeholder: 'Nhập tên'}),
        defineField({name: 'phonePlaceholder', title: 'Phone Input Placeholder', type: 'string', fieldset: 'personal', placeholder: 'Nhập số điện thoại'}),
        defineField({name: 'dobPlaceholder', title: 'Date of Birth Input Placeholder', type: 'string', fieldset: 'personal', placeholder: 'dd/mm/yyyy'}),
        defineField({name: 'emailNotificationsTitle', title: 'Email Alerts Section Header', type: 'string', fieldset: 'personal', placeholder: 'Thông báo qua email'}),
        defineField({name: 'emailNotificationsDescription', title: 'Email Alerts Description', type: 'text', rows: 2, fieldset: 'personal', placeholder: 'Nhận cập nhật quan trọng về tài khoản và hồ sơ qua email.'}),
        {...colorField('personalCardBackgroundColor', 'Card Background Color', '#ffffff'), fieldset: 'personal'},
        {...colorField('personalCardBorderColor', 'Card Border Color', '#e2e8f0'), fieldset: 'personal'},
        {...colorField('personalTextColor', 'Card Text Color', '#0f172a'), fieldset: 'personal'},
        {...colorField('personalMutedTextColor', 'Card Subtext Color', '#64748b'), fieldset: 'personal'},
        {...colorField('personalAccentColor', 'Card Accent Color', '#2563eb'), fieldset: 'personal'},
        defineField({name: 'cvTitle', title: 'CV Section Header Title', type: 'string', fieldset: 'cv', placeholder: 'CV của tôi'}),
        defineField({name: 'uploadNewCvButton', title: 'Upload CV Button Label', type: 'string', fieldset: 'cv', placeholder: 'Tải lên mới'}),
        defineField({name: 'dragDropCvText', title: 'Drag & Drop Guidance Text', type: 'string', fieldset: 'cv', placeholder: 'Kéo thả CV vào đây hoặc bấm để tải lên'}),
        defineField({name: 'cvColumnName', title: 'CV Document Table Column Name', type: 'string', fieldset: 'cv', placeholder: 'CV'}),
        defineField({name: 'cvDefaultColumn', title: 'Default Status Table Column Name', type: 'string', fieldset: 'cv', placeholder: 'Mặc định'}),
        defineField({name: 'setDefaultCvLabel', title: 'Set as Default CV Context Action', type: 'string', fieldset: 'cv', placeholder: 'Đặt {name} làm CV mặc định'}),
        defineField({name: 'deleteCvLabel', title: 'Delete CV Action Label', type: 'string', fieldset: 'cv', placeholder: 'Xóa CV'}),
        {...colorField('cvCardBackgroundColor', 'Card Background Color', '#ffffff'), fieldset: 'cv'},
        {...colorField('cvCardBorderColor', 'Card Border Color', '#e2e8f0'), fieldset: 'cv'},
        {...colorField('cvTextColor', 'Card Text Color', '#0f172a'), fieldset: 'cv'},
        {...colorField('cvMutedTextColor', 'Card Subtext Color', '#64748b'), fieldset: 'cv'},
        {...colorField('cvAccentColor', 'Card Accent Color', '#2563eb'), fieldset: 'cv'},
        defineField({name: 'companyProfileTitle', title: 'Company Details Box Header', type: 'string', fieldset: 'company', placeholder: 'Hồ sơ công ty'}),
        defineField({name: 'companyProfileEmpty', title: 'No Company Profile Text Placeholder', type: 'string', fieldset: 'company', placeholder: 'Chưa có hồ sơ công ty. Bấm để cập nhật.'}),
        defineField({name: 'companyTaxCodeLabel', title: 'Tax Code Label', type: 'string', fieldset: 'company', placeholder: 'Mã số thuế'}),
        defineField({name: 'companyPhoneLabel', title: 'Company Contact Phone Label', type: 'string', fieldset: 'company', placeholder: 'Điện thoại'}),
        defineField({name: 'companyAddressLabel', title: 'Company Office Address Label', type: 'string', fieldset: 'company', placeholder: 'Địa chỉ'}),
        {...colorField('companyCardBackgroundColor', 'Card Background Color', '#ffffff'), fieldset: 'company'},
        {...colorField('companyCardBorderColor', 'Card Border Color', '#e2e8f0'), fieldset: 'company'},
        {...colorField('companyTextColor', 'Card Text Color', '#0f172a'), fieldset: 'company'},
        {...colorField('companyMutedTextColor', 'Card Subtext Color', '#64748b'), fieldset: 'company'},
        {...colorField('companyAccentColor', 'Card Accent Color', '#2563eb'), fieldset: 'company'},
        defineField({name: 'changePasswordTitle', title: 'Reset Password Section Title', type: 'string', fieldset: 'password', placeholder: 'Đổi mật khẩu'}),
        defineField({name: 'currentPasswordPlaceholder', title: 'Current Password Input Placeholder', type: 'string', fieldset: 'password', placeholder: 'Mật khẩu cũ'}),
        defineField({name: 'newPasswordPlaceholder', title: 'New Password Input Placeholder', type: 'string', fieldset: 'password', placeholder: 'Mật khẩu mới'}),
        defineField({name: 'confirmPasswordPlaceholder', title: 'Verify Password Input Placeholder', type: 'string', fieldset: 'password', placeholder: 'Xác nhận mật khẩu'}),
        {...colorField('passwordCardBackgroundColor', 'Card Background Color', '#ffffff'), fieldset: 'password'},
        {...colorField('passwordCardBorderColor', 'Card Border Color', '#e2e8f0'), fieldset: 'password'},
        {...colorField('passwordTextColor', 'Card Text Color', '#0f172a'), fieldset: 'password'},
        {...colorField('passwordMutedTextColor', 'Card Subtext Color', '#64748b'), fieldset: 'password'},
        {...colorField('passwordAccentColor', 'Card Accent Color', '#2563eb'), fieldset: 'password'},
        {...colorField('backgroundColor', 'Page Body Background Color', '#f8fafc'), fieldset: 'style'},
        {...colorField('cardBackgroundColor', 'Standard Card Background Color', '#ffffff'), fieldset: 'style'},
        {...colorField('cardBorderColor', 'Standard Card Border Color', '#e2e8f0'), fieldset: 'style'},
        {...colorField('textColor', 'Standard Primary Text Color', '#0f172a'), fieldset: 'style'},
        {...colorField('mutedTextColor', 'Standard Secondary Text Color', '#64748b'), fieldset: 'style'},
        {...colorField('accentColor', 'Standard Highlight Accent Color', '#2563eb'), fieldset: 'style'},
      ],
    }),
    defineField({
      name: 'homeContent',
      title: 'Default Content — Home Page',
      type: 'object',
      hidden: ({document}) => !isHomePageDocument(document),
      group: 'home',
      description: 'Allows modifying static fields and section items rendering on the main Landing page.',
      fieldsets: [
        {name: 'about', title: 'About Section'},
        {name: 'projectCard', title: 'Project Info Box Card'},
        {name: 'missionCard', title: 'Mission Info Box Card'},
        {name: 'valuesCard', title: 'Core Values Info Box Card'},
        {name: 'featuredJobs', title: 'Featured Job Openings List Header'},
        {name: 'partners', title: 'Partner Grid Section Headers'},
        {name: 'recruiterCta', title: 'Employer Verification Landing Callout'},
        {name: 'footer', title: 'Site Footer Copyright Info'},
      ],
      fields: [
        defineField({name: 'aboutVisible', title: 'Show About Us Section', type: 'boolean', initialValue: true, fieldset: 'about'}),
        {...colorField('aboutSectionBackgroundColor', 'Section Background Color', '#ffffff'), fieldset: 'about'},
        {...colorField('aboutSectionBorderColor', 'Section Border Color', '#e2e8f0'), fieldset: 'about'},
        {...colorField('aboutCardBackgroundColor', 'Main Text Box Background Color', '#ffffff'), fieldset: 'about'},
        {...colorField('aboutCardBorderColor', 'Main Text Box Border Color', '#e2e8f0'), fieldset: 'about'},
        {...colorField('aboutTitleTextColor', 'Main Header Text Color', '#0f172a'), fieldset: 'about'},
        {...colorField('aboutLeadTextColor', 'Hero Lead Accent Text Color', '#2563eb'), fieldset: 'about'},
        {...colorField('aboutBodyTextColor', 'Primary Description Text Color', '#64748b'), fieldset: 'about'},
        ...localizedTextFields('aboutTitle', 'About Section H1 Title').map((field) => ({...field, fieldset: 'about'})),
        ...localizedTextFields('aboutLead', 'About Section Highlight Lead Text', 'text', 2).map((field) => ({...field, fieldset: 'about'})),
        ...localizedTextFields('aboutIntro', 'General Introduction Text block', 'text', 3).map((field) => ({...field, fieldset: 'about'})),
        ...localizedTextFields('aboutIntroLong', 'Detailed Description Text block', 'text', 5).map((field) => ({...field, fieldset: 'about'})),
        defineField({name: 'projectCardVisible', title: 'Show Project Info Card', type: 'boolean', initialValue: true, fieldset: 'projectCard'}),
        {...colorField('projectCardBackgroundColor', 'Card Background Color', '#ffffff'), fieldset: 'projectCard'},
        {...colorField('projectCardBorderColor', 'Card Border Color', '#e2e8f0'), fieldset: 'projectCard'},
        {...colorField('projectCardTitleColor', 'Card Title Text Color', '#0f172a'), fieldset: 'projectCard'},
        {...colorField('projectCardBodyColor', 'Card Body Text Color', '#64748b'), fieldset: 'projectCard'},
        ...localizedTextFields('projectCardTitle', 'Card Heading Title').map((field) => ({...field, fieldset: 'projectCard'})),
        ...localizedTextFields('projectCardBody', 'Card Text Content', 'text', 4).map((field) => ({...field, fieldset: 'projectCard'})),
        defineField({name: 'missionCardVisible', title: 'Show Mission Info Card', type: 'boolean', initialValue: true, fieldset: 'missionCard'}),
        {...colorField('missionCardBackgroundColor', 'Card Background Color', '#ffffff'), fieldset: 'missionCard'},
        {...colorField('missionCardBorderColor', 'Card Border Color', '#e2e8f0'), fieldset: 'missionCard'},
        {...colorField('missionCardTitleColor', 'Card Title Text Color', '#0f172a'), fieldset: 'missionCard'},
        {...colorField('missionCardBodyColor', 'Card Body Text Color', '#64748b'), fieldset: 'missionCard'},
        ...localizedTextFields('missionCardTitle', 'Card Heading Title').map((field) => ({...field, fieldset: 'missionCard'})),
        ...localizedTextFields('missionCardBody', 'Card Text Content', 'text', 4).map((field) => ({...field, fieldset: 'missionCard'})),
        defineField({name: 'valuesCardVisible', title: 'Show Core Values Info Card', type: 'boolean', initialValue: true, fieldset: 'valuesCard'}),
        {...colorField('valuesCardBackgroundColor', 'Card Background Color', '#ffffff'), fieldset: 'valuesCard'},
        {...colorField('valuesCardBorderColor', 'Card Border Color', '#e2e8f0'), fieldset: 'valuesCard'},
        {...colorField('valuesCardTitleColor', 'Card Title Text Color', '#0f172a'), fieldset: 'valuesCard'},
        {...colorField('valuesCardBodyColor', 'Card Body Text Color', '#64748b'), fieldset: 'valuesCard'},
        ...localizedTextFields('valuesCardTitle', 'Card Heading Title').map((field) => ({...field, fieldset: 'valuesCard'})),
        ...localizedTextFields('valuesCardBody', 'Card Text Content', 'text', 4).map((field) => ({...field, fieldset: 'valuesCard'})),
        defineField({name: 'featuredJobsVisible', title: 'Show Featured Jobs Section', type: 'boolean', initialValue: true, fieldset: 'featuredJobs'}),
        ...localizedTextFields('featuredJobsTitle', 'Section H1 Header Title').map((field) => ({...field, fieldset: 'featuredJobs'})),
        ...localizedTextFields('viewAllLabel', 'View All Listings Action Button').map((field) => ({...field, fieldset: 'featuredJobs'})),
        ...localizedTextFields('featuredJobsEmpty', 'Empty Listings State Text Placeholder', 'text', 2).map((field) => ({...field, fieldset: 'featuredJobs'})),
        defineField({name: 'partnersVisible', title: 'Show Partners Grid Section', type: 'boolean', initialValue: true, fieldset: 'partners'}),
        ...localizedTextFields('partnersTitle', 'Partners Section Main H1 Title').map((field) => ({...field, fieldset: 'partners'})),
        ...localizedTextFields('partnersSubtitle', 'Partners Section Supporting Subtitle').map((field) => ({...field, fieldset: 'partners'})),
        ...localizedTextFields('partnersEmpty', 'Empty Partners Grid Label Placeholder', 'text', 2).map((field) => ({...field, fieldset: 'partners'})),
        defineField({name: 'recruiterCtaVisible', title: 'Show Call-to-action Section', type: 'boolean', initialValue: true, fieldset: 'recruiterCta'}),
        ...localizedTextFields('recruiterCtaTitle', 'Call-to-action Header Prompt Title', 'text', 2).map((field) => ({...field, fieldset: 'recruiterCta'})),
        ...localizedTextFields('recruiterCtaButton', 'Recruiter Signup Callout Button Label').map((field) => ({...field, fieldset: 'recruiterCta'})),
        defineField({name: 'footerVisible', title: 'Show Copyright Footer Section', type: 'boolean', initialValue: true, fieldset: 'footer'}),
        ...localizedTextFields('footerText', 'Footer Info Copyright String').map((field) => ({...field, fieldset: 'footer'})),
      ],
    }),
    defineField({
      name: 'sections',
      title: 'Page Dynamic Sections',
      type: 'array',
      description: 'Allows adding, re-ordering, editing, or deleting custom dynamic content sections in the page layout flow.',
      group: 'sections',
      of: [
        {type: 'pageHeroSection'},
        {type: 'pageTextSection'},
        {type: 'pageCardGridSection'},
        {type: 'pageImageTextSection'},
        {type: 'pageImageGallerySection'},
        {type: 'pageCtaSection'},
        {type: 'pageFlexibleSection'},
        {type: 'pageSpacerSection'},
      ],
    }),
    defineField({
      name: 'theme',
      title: 'Interface Colors Accent & Base',
      type: 'object',
      hidden: ({document}) => isHomePageDocument(document),
      group: 'style',
      fields: [
        colorField('pageBackgroundColor', 'Page Body Background Color', '#f8fafc'),
        colorField('headerBackgroundColor', 'Page Header Accent Background Color', '#ffffff'),
        colorField('headerTextColor', 'Page Header Title & Icons Color', '#0f172a'),
        colorField('bodyTextColor', 'General Text Body Color', '#0f172a'),
        colorField('mutedTextColor', 'Supporting Subtitles & Borders Text Color', '#64748b'),
        colorField('cardBackgroundColor', 'Section Grid Card Background Color', '#ffffff'),
        colorField('cardBorderColor', 'Section Grid Card Border Color', '#e2e8f0'),
        colorField('accentColor', 'Action Buttons & Focus States Accent Color', '#2563eb'),
      ],
    }),
    defineField({
      name: 'images',
      title: 'Interface Media Assets',
      type: 'object',
      hidden: ({document}) => isHomePageDocument(document),
      group: 'style',
      fields: [
        defineField({
          name: 'headerImage',
          title: 'Top Banner Background Image',
          type: 'image',
          options: {hotspot: true},
        }),
      ],
    }),
    defineField({
      name: 'homeHero',
      title: 'Landing Page Hero Block',
      type: 'object',
      hidden: ({document}) => !isHomePageDocument(document),
      group: 'home',
      description: 'Customizes the background image, headings, and supporting details in the main Landing Page Hero section.',
      fields: [
        defineField({
          name: 'isVisible',
          title: 'Show Landing Hero Banner',
          type: 'boolean',
          initialValue: true,
        }),
        ...localizedTextFields('title', 'Hero Heading H1 Title'),
        ...localizedTextFields('subtitle', 'Hero Subtitle Prompt text'),
        ...localizedTextFields('description', 'Hero Supporting Description Paragraph', 'text', 3),
        defineField({
          name: 'image',
          title: 'Hero Splash Background Image',
          type: 'image',
          options: {hotspot: true},
        }),
      ],
    }),
    defineField({
      name: 'navbar',
      title: 'Top Navigation Menu Config',
      type: 'object',
      hidden: () => true,
      description: 'Handles navigation items globally. Primary action links (Login / Register) are set by the frontend code.',
      initialValue: {
        isEnabled: true,
        items: defaultNavbarItems,
      },
      fields: [
        defineField({
          name: 'isEnabled',
          title: 'Use custom navigation settings',
          type: 'boolean',
          description: 'Toggle on to override standard frontend navigation items with the definitions set below.',
          initialValue: true,
        }),
        ...localizedTextFields('brandName', 'Brand Title text', 'string', undefined, () => true),
        defineField({
          name: 'logo',
          title: 'Navbar Brand Logo Asset',
          type: 'image',
          hidden: () => true,
          options: {hotspot: true},
        }),
        defineField({
          name: 'showTopBar',
          title: 'Show Global Notification Bar',
          type: 'boolean',
          hidden: () => true,
          initialValue: false,
        }),
        ...localizedTextFields('topBarText', 'Notification Bar Message String', 'string', undefined, () => true),
        colorField('topBarBackgroundColor', 'Notification Bar Background Color', '#0b3f8a', () => true),
        colorField('topBarTextColor', 'Notification Bar Text Color', '#ffffff', () => true),
        colorField('backgroundColor', 'Navigation Menu Background Color', '#ffffff', () => true),
        colorField('textColor', 'Navigation Links Base Color', '#0f172a', () => true),
        colorField('accentColor', 'Navigation Links Highlight Color', '#2563eb', () => true),
        colorField('buttonBackgroundColor', 'Primary CTA (Login) Background Color', '#2563eb', () => true),
        colorField('buttonTextColor', 'Primary CTA (Login) Text Color', '#ffffff', () => true),
        defineField({
          name: 'items',
          title: 'Navigation Menu Links',
          type: 'array',
          initialValue: defaultNavbarItems,
          description: 'Edit, order, show/hide, or delete navbar links. Does not affect fixed Login/Register CTAs.',
          of: [
            {
              type: 'object',
              title: 'Navigation Item',
              fields: [
                defineField({
                  name: 'isVisible',
                  title: 'Show Link',
                  type: 'boolean',
                  initialValue: true,
                }),
                ...localizedTextFields('label', 'Link Display Name'),
                colorField('textColor', 'Custom Link Color Accent', '#0f172a'),
                defineField({
                  name: 'targetId',
                  title: 'Page Anchor Target Section ID',
                  type: 'string',
                  description: 'Scrolls directly to this section ID on click. (e.g. gioi-thieu). Omit if using page route.',
                }),
                defineField({
                  name: 'path',
                  title: 'Destination Page Route Path',
                  type: 'string',
                  description: 'Redirects users to this page route. (e.g. /jobs, /profile). Takes priority over Anchor Target ID.',
                }),
              ],
              validation: (rule) =>
                rule.custom((value: any) =>
                  value?.targetId || value?.path ? true : 'Please configure either a Page Anchor Target Section ID or a Destination Page Route Path.',
                ),
              preview: {
                select: {
                  title: 'label',
                  titleVi: 'labelVi',
                  titleEn: 'labelEn',
                  path: 'path',
                  targetId: 'targetId',
                  isVisible: 'isVisible',
                },
                prepare: ({title, titleVi, titleEn, path, targetId, isVisible}) => ({
                  title: titleEn || title || titleVi || 'Navigation Link Item',
                  subtitle: `${isVisible === false ? 'Hidden · ' : ''}${path || targetId || ''}`,
                }),
              },
            },
          ],
        }),
      ],
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'routePath',
    },
  },
})
