import {defineField, defineType} from 'sanity'
import {ColorInput} from './ColorInput'

const colorField = (
  name: string,
  title: string,
  initialValue: string,
  hidden?: (props: {document?: Record<string, unknown> | null}) => boolean,
) =>
  defineField({
    name,
    title,
    type: 'string',
    initialValue,
    ...(hidden ? {hidden} : {}),
    components: {
      input: ColorInput,
    },
    validation: (rule) =>
      rule.regex(/^#[0-9a-fA-F]{6}$/, {
        name: 'hex color',
        invert: false,
      }),
  })

const localizedTextFields = (
  name: string,
  title: string,
  type: 'string' | 'text' = 'string',
  rows?: number,
  hidden?: (props: {document?: Record<string, unknown> | null}) => boolean,
) => [
  defineField({
    name,
    title: `${title} (mặc định)`,
    type,
    ...(hidden ? {hidden} : {}),
    ...(rows ? {rows} : {}),
  }),
  defineField({
    name: `${name}Vi`,
    title: `${title} tiếng Việt`,
    type,
    ...(hidden ? {hidden} : {}),
    ...(rows ? {rows} : {}),
  }),
  defineField({
    name: `${name}En`,
    title: `${title} tiếng Anh`,
    type,
    ...(hidden ? {hidden} : {}),
    ...(rows ? {rows} : {}),
  }),
]

const isHomePageDocument = (document?: Record<string, unknown> | null) => document?.routePath === '/'

const defaultNavbarItems = [
  {
    _type: 'object',
    _key: 'about',
    isVisible: true,
    label: 'Giới thiệu',
    labelVi: 'Giới thiệu',
    labelEn: 'About',
    targetId: 'gioi-thieu',
  },
  {
    _type: 'object',
    _key: 'featured-jobs',
    isVisible: true,
    label: 'Việc làm nổi bật',
    labelVi: 'Việc làm nổi bật',
    labelEn: 'Featured jobs',
    targetId: 'viec-lam-noi-bat',
  },
  {
    _type: 'object',
    _key: 'partners',
    isVisible: true,
    label: 'Đối tác',
    labelVi: 'Đối tác',
    labelEn: 'Partners',
    targetId: 'doi-tac',
  },
  {
    _type: 'object',
    _key: 'recruitment',
    isVisible: true,
    label: 'Tuyển dụng',
    labelVi: 'Tuyển dụng',
    labelEn: 'Recruitment',
    targetId: 'tuyen-dung',
  },
]

export const managedPage = defineType({
  name: 'managedPage',
  title: 'Quản lý trang',
  type: 'document',
  groups: [
    {name: 'content', title: 'Nội dung có sẵn', hidden: ({document}) => isHomePageDocument(document)},
    {name: 'sections', title: 'Section thêm/xóa', default: true},
    {name: 'style', title: 'Giao diện', hidden: ({document}) => isHomePageDocument(document)},
    {name: 'home', title: 'Nội dung trang chủ', hidden: ({document}) => !isHomePageDocument(document)},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Tên trang',
      type: 'string',
      hidden: ({document}) => isHomePageDocument(document),
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'routePath',
      title: 'Đường dẫn trang',
      type: 'string',
      hidden: ({document}) => isHomePageDocument(document),
      description: 'Frontend dùng đường dẫn này để lấy cả nội dung giao diện và section động.',
      initialValue: '/',
      options: {
        list: [
          {title: 'Trang chủ', value: '/'},
          {title: 'Việc làm', value: '/jobs'},
          {title: 'Hồ sơ cá nhân', value: '/profile'},
          {title: 'Ứng tuyển', value: '/applications'},
          {title: 'Xác thực nhà tuyển dụng', value: '/recruiter-verification'},
          {title: 'Dashboard admin', value: '/admin'},
          {title: 'Dashboard nhà tuyển dụng', value: '/recruiter'},
          {title: 'Dashboard kiểm duyệt', value: '/moderator'},
        ],
      },
      validation: (rule) =>
        rule
          .required()
          .custom((value) =>
            value === '/login' || value === '/register'
              ? 'Login và Register được quản lý bằng document Sanity riêng.'
              : true,
          ),
    }),
    defineField({
      name: 'texts',
      title: 'Nội dung giao diện có sẵn',
      type: 'array',
      hidden: () => true,
      description: 'Dùng để sửa chữ của các phần frontend đã có sẵn, ví dụ Giới thiệu dự án hoặc tiêu đề trang.',
      group: 'content',
      of: [{type: 'managedInterfaceText'}],
    }),
    defineField({name: 'jobsContent', title: 'Nội dung mặc định trang việc làm', type: 'jobsPageContent', hidden: ({document}) => document?.routePath !== '/jobs', group: 'content'}),
    defineField({name: 'applicationsContent', title: 'Nội dung mặc định trang ứng tuyển', type: 'applicationsPageContent', hidden: ({document}) => document?.routePath !== '/applications', group: 'content'}),
    defineField({name: 'verificationContent', title: 'Nội dung mặc định trang xác thực', type: 'verificationPageContent', hidden: ({document}) => document?.routePath !== '/recruiter-verification', group: 'content'}),
    defineField({name: 'adminContent', title: 'Nội dung mặc định Dashboard Admin', type: 'adminPageContent', hidden: ({document}) => document?.routePath !== '/admin', group: 'content'}),
    defineField({name: 'recruiterContent', title: 'Nội dung mặc định Dashboard nhà tuyển dụng', type: 'recruiterPageContent', hidden: ({document}) => document?.routePath !== '/recruiter', group: 'content'}),
    defineField({name: 'moderatorContent', title: 'Nội dung mặc định Dashboard kiểm duyệt', type: 'moderatorPageContent', hidden: ({document}) => document?.routePath !== '/moderator', group: 'content'}),
    defineField({
      name: 'profileDefaults',
      title: 'Profile default layout',
      type: 'object',
      hidden: ({document}) => document?.routePath !== '/profile',
      group: 'content',
      description: 'Chỉnh chữ của các khối mặc định trong trang Profile, không cần nhập mã key thủ công.',
      fieldsets: [
        {name: 'personal', title: 'Thông tin cá nhân', options: {columns: 2}},
        {name: 'cv', title: 'CV', options: {columns: 2}},
        {name: 'company', title: 'Hồ sơ công ty', options: {columns: 2}},
        {name: 'password', title: 'Đổi mật khẩu', options: {columns: 2}},
        {name: 'style', title: 'Màu sắc', options: {columns: 2}},
      ],
      fields: [
        defineField({
          name: 'isVisible',
          title: 'Hiển thị',
          type: 'boolean',
          initialValue: true,
          description: 'Tắt để frontend bỏ qua các nội dung trong Profile default layout.',
        }),
        defineField({name: 'editButton', title: 'Nút chỉnh sửa', type: 'string', fieldset: 'personal'}),
        defineField({name: 'cancelButton', title: 'Nút hủy', type: 'string', fieldset: 'personal'}),
        defineField({name: 'saveButton', title: 'Nút lưu', type: 'string', fieldset: 'personal'}),
        defineField({name: 'lastNameLabel', title: 'Nhãn họ', type: 'string', fieldset: 'personal'}),
        defineField({name: 'firstNameLabel', title: 'Nhãn tên', type: 'string', fieldset: 'personal'}),
        defineField({name: 'phoneLabel', title: 'Nhãn số điện thoại', type: 'string', fieldset: 'personal'}),
        defineField({name: 'dobLabel', title: 'Nhãn ngày sinh', type: 'string', fieldset: 'personal'}),
        defineField({name: 'genderLabel', title: 'Nhãn giới tính', type: 'string', fieldset: 'personal'}),
        defineField({name: 'emailLabel', title: 'Nhãn email', type: 'string', fieldset: 'personal'}),
        defineField({name: 'selectPlaceholder', title: 'Placeholder chọn', type: 'string', fieldset: 'personal'}),
        defineField({name: 'lastNamePlaceholder', title: 'Placeholder họ', type: 'string', fieldset: 'personal'}),
        defineField({name: 'firstNamePlaceholder', title: 'Placeholder tên', type: 'string', fieldset: 'personal'}),
        defineField({name: 'phonePlaceholder', title: 'Placeholder số điện thoại', type: 'string', fieldset: 'personal'}),
        defineField({name: 'dobPlaceholder', title: 'Placeholder ngày sinh', type: 'string', fieldset: 'personal'}),
        defineField({name: 'emailNotificationsTitle', title: 'Tiêu đề thông báo email', type: 'string', fieldset: 'personal'}),
        defineField({name: 'emailNotificationsDescription', title: 'Mô tả thông báo email', type: 'text', rows: 2, fieldset: 'personal'}),
        {...colorField('personalCardBackgroundColor', 'Màu nền thẻ', '#ffffff'), fieldset: 'personal'},
        {...colorField('personalCardBorderColor', 'Màu viền thẻ', '#e2e8f0'), fieldset: 'personal'},
        {...colorField('personalTextColor', 'Màu chữ', '#0f172a'), fieldset: 'personal'},
        {...colorField('personalMutedTextColor', 'Màu chữ phụ', '#64748b'), fieldset: 'personal'},
        {...colorField('personalAccentColor', 'Màu nhấn', '#2563eb'), fieldset: 'personal'},
        defineField({name: 'cvTitle', title: 'Tiêu đề khối CV', type: 'string', fieldset: 'cv'}),
        defineField({name: 'uploadNewCvButton', title: 'Nút tải CV', type: 'string', fieldset: 'cv'}),
        defineField({name: 'dragDropCvText', title: 'Hướng dẫn kéo thả CV', type: 'string', fieldset: 'cv'}),
        defineField({name: 'cvColumnName', title: 'Cột CV', type: 'string', fieldset: 'cv'}),
        defineField({name: 'cvDefaultColumn', title: 'Cột mặc định', type: 'string', fieldset: 'cv'}),
        defineField({name: 'setDefaultCvLabel', title: 'Nhãn đặt mặc định', type: 'string', fieldset: 'cv'}),
        defineField({name: 'deleteCvLabel', title: 'Nhãn xóa CV', type: 'string', fieldset: 'cv'}),
        {...colorField('cvCardBackgroundColor', 'Màu nền thẻ', '#ffffff'), fieldset: 'cv'},
        {...colorField('cvCardBorderColor', 'Màu viền thẻ', '#e2e8f0'), fieldset: 'cv'},
        {...colorField('cvTextColor', 'Màu chữ', '#0f172a'), fieldset: 'cv'},
        {...colorField('cvMutedTextColor', 'Màu chữ phụ', '#64748b'), fieldset: 'cv'},
        {...colorField('cvAccentColor', 'Màu nhấn', '#2563eb'), fieldset: 'cv'},
        defineField({name: 'companyProfileTitle', title: 'Tiêu đề hồ sơ công ty', type: 'string', fieldset: 'company'}),
        defineField({name: 'companyProfileEmpty', title: 'Thông báo chưa có hồ sơ', type: 'string', fieldset: 'company'}),
        defineField({name: 'companyTaxCodeLabel', title: 'Nhãn mã số thuế', type: 'string', fieldset: 'company'}),
        defineField({name: 'companyPhoneLabel', title: 'Nhãn điện thoại', type: 'string', fieldset: 'company'}),
        defineField({name: 'companyAddressLabel', title: 'Nhãn địa chỉ', type: 'string', fieldset: 'company'}),
        {...colorField('companyCardBackgroundColor', 'Màu nền thẻ', '#ffffff'), fieldset: 'company'},
        {...colorField('companyCardBorderColor', 'Màu viền thẻ', '#e2e8f0'), fieldset: 'company'},
        {...colorField('companyTextColor', 'Màu chữ', '#0f172a'), fieldset: 'company'},
        {...colorField('companyMutedTextColor', 'Màu chữ phụ', '#64748b'), fieldset: 'company'},
        {...colorField('companyAccentColor', 'Màu nhấn', '#2563eb'), fieldset: 'company'},
        defineField({name: 'changePasswordTitle', title: 'Tiêu đề đổi mật khẩu', type: 'string', fieldset: 'password'}),
        defineField({name: 'currentPasswordPlaceholder', title: 'Placeholder mật khẩu cũ', type: 'string', fieldset: 'password'}),
        defineField({name: 'newPasswordPlaceholder', title: 'Placeholder mật khẩu mới', type: 'string', fieldset: 'password'}),
        defineField({name: 'confirmPasswordPlaceholder', title: 'Placeholder xác nhận mật khẩu', type: 'string', fieldset: 'password'}),
        {...colorField('passwordCardBackgroundColor', 'Màu nền thẻ', '#ffffff'), fieldset: 'password'},
        {...colorField('passwordCardBorderColor', 'Màu viền thẻ', '#e2e8f0'), fieldset: 'password'},
        {...colorField('passwordTextColor', 'Màu chữ', '#0f172a'), fieldset: 'password'},
        {...colorField('passwordMutedTextColor', 'Màu chữ phụ', '#64748b'), fieldset: 'password'},
        {...colorField('passwordAccentColor', 'Màu nhấn', '#2563eb'), fieldset: 'password'},
        {...colorField('backgroundColor', 'Màu nền khu vực', '#f8fafc'), fieldset: 'style'},
        {...colorField('cardBackgroundColor', 'Màu nền thẻ', '#ffffff'), fieldset: 'style'},
        {...colorField('cardBorderColor', 'Màu viền thẻ', '#e2e8f0'), fieldset: 'style'},
        {...colorField('textColor', 'Màu chữ chính', '#0f172a'), fieldset: 'style'},
        {...colorField('mutedTextColor', 'Màu chữ phụ', '#64748b'), fieldset: 'style'},
        {...colorField('accentColor', 'Màu nhấn', '#2563eb'), fieldset: 'style'},
      ],
    }),
    defineField({
      name: 'homeContent',
      title: 'Nội dung các khối trang chủ',
      type: 'object',
      hidden: ({document}) => !isHomePageDocument(document),
      group: 'home',
      description: 'Chỉnh nội dung các khối và card có sẵn trên trang chủ. Để trống sẽ dùng bản dịch mặc định của website.',
      fieldsets: [
        {name: 'about', title: 'Giới thiệu', options: {columns: 1}},
        {name: 'projectCard', title: 'Card Dự án', options: {columns: 1}},
        {name: 'missionCard', title: 'Card Sứ mệnh', options: {columns: 1}},
        {name: 'valuesCard', title: 'Card Giá trị', options: {columns: 1}},
        {name: 'featuredJobs', title: 'Việc làm nổi bật', options: {columns: 1}},
        {name: 'partners', title: 'Đối tác', options: {columns: 1}},
        {name: 'recruiterCta', title: 'Kêu gọi nhà tuyển dụng', options: {columns: 1}},
        {name: 'footer', title: 'Chân trang', options: {columns: 1}},
      ],
      fields: [
        defineField({name: 'aboutVisible', title: 'Hiển thị section Giới thiệu', type: 'boolean', initialValue: true, fieldset: 'about'}),
        {...colorField('aboutSectionBackgroundColor', 'Màu nền section', '#ffffff'), fieldset: 'about'},
        {...colorField('aboutSectionBorderColor', 'Màu viền section', '#e2e8f0'), fieldset: 'about'},
        {...colorField('aboutCardBackgroundColor', 'Màu nền ô lớn', '#ffffff'), fieldset: 'about'},
        {...colorField('aboutCardBorderColor', 'Màu viền ô lớn', '#e2e8f0'), fieldset: 'about'},
        {...colorField('aboutTitleTextColor', 'Màu tiêu đề', '#0f172a'), fieldset: 'about'},
        {...colorField('aboutLeadTextColor', 'Màu câu nhấn', '#2563eb'), fieldset: 'about'},
        {...colorField('aboutBodyTextColor', 'Màu nội dung', '#64748b'), fieldset: 'about'},
        ...localizedTextFields('aboutTitle', 'Tiêu đề giới thiệu').map((field) => ({...field, fieldset: 'about'})),
        ...localizedTextFields('aboutLead', 'Câu nhấn giới thiệu', 'text', 2).map((field) => ({...field, fieldset: 'about'})),
        ...localizedTextFields('aboutIntro', 'Mô tả ngắn', 'text', 3).map((field) => ({...field, fieldset: 'about'})),
        ...localizedTextFields('aboutIntroLong', 'Mô tả chi tiết', 'text', 5).map((field) => ({...field, fieldset: 'about'})),
        defineField({name: 'projectCardVisible', title: 'Hiển thị card', type: 'boolean', initialValue: true, fieldset: 'projectCard'}),
        {...colorField('projectCardBackgroundColor', 'Màu nền', '#ffffff'), fieldset: 'projectCard'},
        {...colorField('projectCardBorderColor', 'Màu viền', '#e2e8f0'), fieldset: 'projectCard'},
        {...colorField('projectCardTitleColor', 'Màu tiêu đề', '#0f172a'), fieldset: 'projectCard'},
        {...colorField('projectCardBodyColor', 'Màu nội dung', '#64748b'), fieldset: 'projectCard'},
        ...localizedTextFields('projectCardTitle', 'Tiêu đề card').map((field) => ({...field, fieldset: 'projectCard'})),
        ...localizedTextFields('projectCardBody', 'Nội dung card', 'text', 4).map((field) => ({...field, fieldset: 'projectCard'})),
        defineField({name: 'missionCardVisible', title: 'Hiển thị card', type: 'boolean', initialValue: true, fieldset: 'missionCard'}),
        {...colorField('missionCardBackgroundColor', 'Màu nền', '#ffffff'), fieldset: 'missionCard'},
        {...colorField('missionCardBorderColor', 'Màu viền', '#e2e8f0'), fieldset: 'missionCard'},
        {...colorField('missionCardTitleColor', 'Màu tiêu đề', '#0f172a'), fieldset: 'missionCard'},
        {...colorField('missionCardBodyColor', 'Màu nội dung', '#64748b'), fieldset: 'missionCard'},
        ...localizedTextFields('missionCardTitle', 'Tiêu đề card').map((field) => ({...field, fieldset: 'missionCard'})),
        ...localizedTextFields('missionCardBody', 'Nội dung card', 'text', 4).map((field) => ({...field, fieldset: 'missionCard'})),
        defineField({name: 'valuesCardVisible', title: 'Hiển thị card', type: 'boolean', initialValue: true, fieldset: 'valuesCard'}),
        {...colorField('valuesCardBackgroundColor', 'Màu nền', '#ffffff'), fieldset: 'valuesCard'},
        {...colorField('valuesCardBorderColor', 'Màu viền', '#e2e8f0'), fieldset: 'valuesCard'},
        {...colorField('valuesCardTitleColor', 'Màu tiêu đề', '#0f172a'), fieldset: 'valuesCard'},
        {...colorField('valuesCardBodyColor', 'Màu nội dung', '#64748b'), fieldset: 'valuesCard'},
        ...localizedTextFields('valuesCardTitle', 'Tiêu đề card').map((field) => ({...field, fieldset: 'valuesCard'})),
        ...localizedTextFields('valuesCardBody', 'Nội dung card', 'text', 4).map((field) => ({...field, fieldset: 'valuesCard'})),
        defineField({name: 'featuredJobsVisible', title: 'Hiển thị section', type: 'boolean', initialValue: true, fieldset: 'featuredJobs'}),
        ...localizedTextFields('featuredJobsTitle', 'Tiêu đề khu vực').map((field) => ({...field, fieldset: 'featuredJobs'})),
        ...localizedTextFields('viewAllLabel', 'Nút xem tất cả').map((field) => ({...field, fieldset: 'featuredJobs'})),
        ...localizedTextFields('featuredJobsEmpty', 'Thông báo khi chưa có việc làm', 'text', 2).map((field) => ({...field, fieldset: 'featuredJobs'})),
        defineField({name: 'partnersVisible', title: 'Hiển thị section', type: 'boolean', initialValue: true, fieldset: 'partners'}),
        ...localizedTextFields('partnersTitle', 'Tiêu đề đối tác').map((field) => ({...field, fieldset: 'partners'})),
        ...localizedTextFields('partnersSubtitle', 'Phụ đề đối tác').map((field) => ({...field, fieldset: 'partners'})),
        ...localizedTextFields('partnersEmpty', 'Thông báo khi chưa có đối tác', 'text', 2).map((field) => ({...field, fieldset: 'partners'})),
        defineField({name: 'recruiterCtaVisible', title: 'Hiển thị section', type: 'boolean', initialValue: true, fieldset: 'recruiterCta'}),
        ...localizedTextFields('recruiterCtaTitle', 'Tiêu đề kêu gọi', 'text', 2).map((field) => ({...field, fieldset: 'recruiterCta'})),
        ...localizedTextFields('recruiterCtaButton', 'Nút xác thực').map((field) => ({...field, fieldset: 'recruiterCta'})),
        defineField({name: 'footerVisible', title: 'Hiển thị footer', type: 'boolean', initialValue: true, fieldset: 'footer'}),
        ...localizedTextFields('footerText', 'Nội dung chân trang').map((field) => ({...field, fieldset: 'footer'})),
      ],
    }),
    defineField({
      name: 'sections',
      title: 'Section thêm/xóa',
      type: 'array',
      description: 'Admin có thể thêm, xóa, ẩn/hiện và kéo thả thứ tự section tại đây.',
      group: 'sections',
      of: [
        {type: 'pageHeroSection'},
        {type: 'pageTextSection'},
        {type: 'pageCardGridSection'},
        {type: 'pageImageTextSection'},
         {type: 'pageImageGallerySection'},
        {type: 'pageCtaSection'},
        {type: 'pageFlexibleSection'},
        {type: 'pageSpacerSection'},
      ],
    }),
    defineField({
      name: 'theme',
      title: 'Màu sắc giao diện',
      type: 'object',
      hidden: ({document}) => isHomePageDocument(document),
      group: 'style',
      fields: [
        colorField('pageBackgroundColor', 'Màu nền trang', '#f8fafc'),
        colorField('headerBackgroundColor', 'Màu nền phần đầu trang', '#ffffff'),
        colorField('headerTextColor', 'Màu chữ phần đầu trang', '#0f172a'),
        colorField('bodyTextColor', 'Màu chữ nội dung', '#0f172a'),
        colorField('mutedTextColor', 'Màu chữ phụ', '#64748b'),
        colorField('cardBackgroundColor', 'Màu nền thẻ', '#ffffff'),
        colorField('cardBorderColor', 'Màu viền thẻ', '#e2e8f0'),
        colorField('accentColor', 'Màu nhấn', '#2563eb'),
      ],
    }),
    defineField({
      name: 'images',
      title: 'Hình ảnh giao diện',
      type: 'object',
      hidden: ({document}) => isHomePageDocument(document),
      group: 'style',
      fields: [
        defineField({
          name: 'headerImage',
          title: 'Hình đầu trang',
          type: 'image',
          options: {hotspot: true},
        }),
      ],
    }),
    defineField({
      name: 'homeHero',
      title: 'Home hero',
      type: 'object',
      hidden: ({document}) => !isHomePageDocument(document),
      group: 'home',
      description: 'Chỉnh ảnh lớn, tiêu đề và nội dung hero ở trang chủ.',
      fields: [
        defineField({
          name: 'isVisible',
          title: 'Hiển thị Hero',
          type: 'boolean',
          initialValue: true,
        }),
        ...localizedTextFields('title', 'Tiêu đề hero'),
        ...localizedTextFields('subtitle', 'Phụ đề hero'),
        ...localizedTextFields('description', 'Mô tả hero', 'text', 3),
        defineField({
          name: 'image',
          title: 'Ảnh nền hero',
          type: 'image',
          options: {hotspot: true},
        }),
      ],
    }),
    defineField({
      name: 'navbar',
      title: 'Header/navbar',
      type: 'object',
      hidden: () => true,
      description: 'Quản lý các mục menu trong header. Nút Đăng nhập và Đăng ký vẫn được giữ cố định ngoài danh sách này.',
      initialValue: {
        isEnabled: true,
        items: defaultNavbarItems,
      },
      fields: [
        defineField({
          name: 'isEnabled',
          title: 'Dùng danh sách menu từ Sanity',
          type: 'boolean',
          description: 'Bật để frontend dùng danh sách bên dưới thay cho menu mặc định.',
          initialValue: true,
        }),
        ...localizedTextFields('brandName', 'Tên thương hiệu', 'string', undefined, () => true),
        defineField({
          name: 'logo',
          title: 'Logo',
          type: 'image',
          hidden: () => true,
          options: {hotspot: true},
        }),
        defineField({
          name: 'showTopBar',
          title: 'Hiển thị thanh thông báo trên cùng',
          type: 'boolean',
          hidden: () => true,
          initialValue: false,
        }),
        ...localizedTextFields('topBarText', 'Nội dung thanh thông báo', 'string', undefined, () => true),
        colorField('topBarBackgroundColor', 'Màu nền thanh thông báo', '#0b3f8a', () => true),
        colorField('topBarTextColor', 'Màu chữ thanh thông báo', '#ffffff', () => true),
        colorField('backgroundColor', 'Màu nền thanh điều hướng', '#ffffff', () => true),
        colorField('textColor', 'Màu chữ thanh điều hướng', '#0f172a', () => true),
        colorField('accentColor', 'Màu nhấn', '#2563eb', () => true),
        colorField('buttonBackgroundColor', 'Màu nút đăng nhập', '#2563eb', () => true),
        colorField('buttonTextColor', 'Màu chữ nút đăng nhập', '#ffffff', () => true),
        defineField({
          name: 'items',
          title: 'Các mục trong header/navbar',
          type: 'array',
          initialValue: defaultNavbarItems,
          description: 'Thêm, xóa, chỉnh sửa, ẩn/hiện, đổi màu và kéo thả thứ tự các mục menu. Không bao gồm nút Đăng nhập/Đăng ký.',
          of: [
            {
              type: 'object',
              title: 'Mục menu',
              fields: [
                defineField({
                  name: 'isVisible',
                  title: 'Hiển thị',
                  type: 'boolean',
                  initialValue: true,
                }),
                ...localizedTextFields('label', 'Tên mục'),
                colorField('textColor', 'Màu chữ', '#0f172a'),
                defineField({
                  name: 'targetId',
                  title: 'ID section để cuộn tới',
                  type: 'string',
                  description: 'Dùng cho link cuộn trong trang chủ, ví dụ: gioi-thieu. Để trống nếu dùng đường dẫn trang.',
                }),
                defineField({
                  name: 'path',
                  title: 'Đường dẫn trang',
                  type: 'string',
                  description: 'Tùy chọn. Ví dụ /jobs, /profile. Nếu nhập mục này thì sẽ ưu tiên hơn ID section.',
                }),
              ],
              validation: (rule) =>
                rule.custom((value) =>
                  value?.targetId || value?.path ? true : 'Nhập ID section hoặc đường dẫn trang.',
                ),
              preview: {
                select: {
                  title: 'label',
                  titleVi: 'labelVi',
                  titleEn: 'labelEn',
                  path: 'path',
                  targetId: 'targetId',
                  isVisible: 'isVisible',
                },
                prepare: ({title, titleVi, titleEn, path, targetId, isVisible}) => ({
                  title: titleVi || title || titleEn || 'Mục menu',
                  subtitle: `${isVisible === false ? 'Đang ẩn · ' : ''}${path || targetId || ''}`,
                }),
              },
            },
          ],
        }),
      ],
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'routePath',
    },
  },
})
