import {defineField, defineType} from 'sanity'
import {ColorInput} from './ColorInput'

export const registerHero = defineType({
  name: 'registerHero',
  title: 'Register Hero',
  type: 'document',
  fields: [
    defineField({
      name: 'badge',
      title: 'Badge (mặc định)',
      type: 'string',
      initialValue: 'New candidate',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'badgeVi',
      title: 'Badge tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'badgeEn',
      title: 'Badge tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'title',
      title: 'Title (mặc định)',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'titleVi',
      title: 'Title tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'titleEn',
      title: 'Title tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'description',
      title: 'Description (mặc định)',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'descriptionVi',
      title: 'Description tiếng Việt',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'descriptionEn',
      title: 'Description tiếng Anh',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'noteTitle',
      title: 'Bottom Card Title (mặc định)',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'noteTitleVi',
      title: 'Bottom Card Title tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'noteTitleEn',
      title: 'Bottom Card Title tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'noteText',
      title: 'Bottom Card Text (mặc định)',
      type: 'text',
      rows: 2,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'noteTextVi',
      title: 'Bottom Card Text tiếng Việt',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'noteTextEn',
      title: 'Bottom Card Text tiếng Anh',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'backgroundColor',
      title: 'Background Color',
      type: 'string',
      initialValue: '#f1f5f9',
      components: {
        input: ColorInput,
      },
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, {
        name: 'hex color',
        invert: false,
      }),
    }),
    defineField({
      name: 'textColor',
      title: 'Text Color',
      type: 'string',
      initialValue: '#0f172a',
      components: {
        input: ColorInput,
      },
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, {
        name: 'hex color',
        invert: false,
      }),
    }),
    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      options: {hotspot: true},
    }),
    defineField({
      name: 'formTitle',
      title: 'Form Title (mặc định)',
      type: 'string',
      initialValue: 'Đăng ký tài khoản',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'formTitleVi',
      title: 'Form Title tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'formTitleEn',
      title: 'Form Title tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'formDescription',
      title: 'Form Description (mặc định)',
      type: 'text',
      rows: 2,
      initialValue: 'Hoàn tất thông tin bên dưới để tạo tài khoản ứng viên.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'formDescriptionVi',
      title: 'Form Description tiếng Việt',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'formDescriptionEn',
      title: 'Form Description tiếng Anh',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'lastNameLabel',
      title: 'Last Name Label (mặc định)',
      type: 'string',
      initialValue: 'Họ',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'lastNameLabelVi',
      title: 'Last Name Label tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'lastNameLabelEn',
      title: 'Last Name Label tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'lastNamePlaceholder',
      title: 'Last Name Placeholder (mặc định)',
      type: 'string',
      initialValue: 'Nguyen',
    }),
    defineField({
      name: 'lastNamePlaceholderVi',
      title: 'Last Name Placeholder tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'lastNamePlaceholderEn',
      title: 'Last Name Placeholder tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'firstNameLabel',
      title: 'First Name Label (mặc định)',
      type: 'string',
      initialValue: 'Tên',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'firstNameLabelVi',
      title: 'First Name Label tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'firstNameLabelEn',
      title: 'First Name Label tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'firstNamePlaceholder',
      title: 'First Name Placeholder (mặc định)',
      type: 'string',
      initialValue: 'An',
    }),
    defineField({
      name: 'firstNamePlaceholderVi',
      title: 'First Name Placeholder tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'firstNamePlaceholderEn',
      title: 'First Name Placeholder tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'emailLabel',
      title: 'Email Label (mặc định)',
      type: 'string',
      initialValue: 'Email',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'emailLabelVi',
      title: 'Email Label tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'emailLabelEn',
      title: 'Email Label tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'emailPlaceholder',
      title: 'Email Placeholder (mặc định)',
      type: 'string',
      initialValue: 'ten@example.com',
    }),
    defineField({
      name: 'emailPlaceholderVi',
      title: 'Email Placeholder tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'emailPlaceholderEn',
      title: 'Email Placeholder tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'phoneLabel',
      title: 'Phone Label (mặc định)',
      type: 'string',
      initialValue: 'Số điện thoại',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'phoneLabelVi',
      title: 'Phone Label tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'phoneLabelEn',
      title: 'Phone Label tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'phonePlaceholder',
      title: 'Phone Placeholder (mặc định)',
      type: 'string',
      initialValue: '0901234567',
    }),
    defineField({
      name: 'phonePlaceholderVi',
      title: 'Phone Placeholder tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'phonePlaceholderEn',
      title: 'Phone Placeholder tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'passwordLabel',
      title: 'Password Label (mặc định)',
      type: 'string',
      initialValue: 'Mật khẩu',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'passwordLabelVi',
      title: 'Password Label tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'passwordLabelEn',
      title: 'Password Label tiếng Anh',
      type: 'string',
    }),
    defineField({
      name: 'passwordPlaceholder',
      title: 'Password Placeholder (mặc định)',
      type: 'string',
      initialValue: 'Tối thiểu 6 ký tự',
    }),
    defineField({
      name: 'passwordPlaceholderVi',
      title: 'Password Placeholder tiếng Việt',
      type: 'string',
    }),
    defineField({
      name: 'passwordPlaceholderEn',
      title: 'Password Placeholder tiếng Anh',
      type: 'string',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'description',
      media: 'image',
    },
  },
})
