import {defineField, defineType} from 'sanity'
import {ColorInput} from './ColorInput'

export const registerHero = defineType({
  name: 'registerHero',
  title: 'Register Form Customizer',
  type: 'document',
  fields: [
    defineField({
      name: 'badge',
      title: 'Hero Welcome Badge (Default)',
      type: 'string',
      initialValue: 'New candidate',
      placeholder: 'Ứng viên mới',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'badgeVi',
      title: 'Hero Welcome Badge VI',
      type: 'string',
      placeholder: 'Ứng viên mới',
    }),
    defineField({
      name: 'badgeEn',
      title: 'Hero Welcome Badge EN',
      type: 'string',
      placeholder: 'New candidate',
    }),
    defineField({
      name: 'title',
      title: 'Hero Welcome Header (Default)',
      type: 'string',
      placeholder: 'Tạo hồ sơ để bắt đầu hành trình thực tập',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'titleVi',
      title: 'Hero Welcome Header VI',
      type: 'string',
      placeholder: 'Tạo hồ sơ để bắt đầu hành trình thực tập',
    }),
    defineField({
      name: 'titleEn',
      title: 'Hero Welcome Header EN',
      type: 'string',
      placeholder: 'Create a profile to start your internship journey',
    }),
    defineField({
      name: 'description',
      title: 'Hero Description Paragraph (Default)',
      type: 'text',
      rows: 3,
      placeholder: 'Đăng ký tài khoản ứng viên để theo dõi chương trình, cập nhật hồ sơ và kết nối với các doanh nghiệp phù hợp.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'descriptionVi',
      title: 'Hero Description Paragraph VI',
      type: 'text',
      rows: 3,
      placeholder: 'Đăng ký tài khoản ứng viên để theo dõi chương trình, cập nhật hồ sơ và kết nối với các doanh nghiệp phù hợp.',
    }),
    defineField({
      name: 'descriptionEn',
      title: 'Hero Description Paragraph EN',
      type: 'text',
      rows: 3,
      placeholder: 'Register a candidate account to follow programs, update your profile, and connect with suitable companies.',
    }),
    defineField({
      name: 'noteTitle',
      title: 'Hero Bottom Card Alert Header (Default)',
      type: 'string',
      placeholder: 'Tài khoản mới mặc định là tài khoản ứng viên.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'noteTitleVi',
      title: 'Hero Bottom Card Alert Header VI',
      type: 'string',
      placeholder: 'Tài khoản mới mặc định là tài khoản ứng viên.',
    }),
    defineField({
      name: 'noteTitleEn',
      title: 'Hero Bottom Card Alert Header EN',
      type: 'string',
      placeholder: 'New accounts are candidate accounts by default.',
    }),
    defineField({
      name: 'noteText',
      title: 'Hero Bottom Card Alert Message (Default)',
      type: 'text',
      rows: 2,
      placeholder: 'Bạn là nhà tuyển dụng? Sau khi tạo tài khoản, hãy gửi yêu cầu xác thực để nhận quyền.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'noteTextVi',
      title: 'Hero Bottom Card Alert Message VI',
      type: 'text',
      rows: 2,
      placeholder: 'Bạn là nhà tuyển dụng? Sau khi tạo tài khoản, hãy gửi yêu cầu xác thực để nhận quyền.',
    }),
    defineField({
      name: 'noteTextEn',
      title: 'Hero Bottom Card Alert Message EN',
      type: 'text',
      rows: 2,
      placeholder: 'Are you a recruiter? After creating an account, request verification to receive permissions.',
    }),
    defineField({
      name: 'backgroundColor',
      title: 'Left Block Background Color',
      type: 'string',
      initialValue: '#f1f5f9',
      components: {
        input: ColorInput,
      },
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, {
        name: 'hex color',
        invert: false,
      }),
    }),
    defineField({
      name: 'textColor',
      title: 'Left Block Text Color Accent',
      type: 'string',
      initialValue: '#0f172a',
      components: {
        input: ColorInput,
      },
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, {
        name: 'hex color',
        invert: false,
      }),
    }),
    defineField({
      name: 'image',
      title: 'Left Block Side Illustration',
      type: 'image',
      options: {hotspot: true},
    }),
    defineField({
      name: 'formTitle',
      title: 'Form Heading H1 (Default)',
      type: 'string',
      initialValue: 'Đăng ký tài khoản',
      placeholder: 'Đăng ký tài khoản',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'formTitleVi',
      title: 'Form Heading H1 VI',
      type: 'string',
      placeholder: 'Đăng ký tài khoản',
    }),
    defineField({
      name: 'formTitleEn',
      title: 'Form Heading H1 EN',
      type: 'string',
      placeholder: 'Register account',
    }),
    defineField({
      name: 'formDescription',
      title: 'Form Supporting Subtitle (Default)',
      type: 'text',
      rows: 2,
      initialValue: 'Hoàn tất thông tin bên dưới để tạo tài khoản ứng viên.',
      placeholder: 'Hoàn tất thông tin bên dưới để tạo tài khoản ứng viên.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'formDescriptionVi',
      title: 'Form Supporting Subtitle VI',
      type: 'text',
      rows: 2,
      placeholder: 'Hoàn tất thông tin bên dưới để tạo tài khoản ứng viên.',
    }),
    defineField({
      name: 'formDescriptionEn',
      title: 'Form Supporting Subtitle EN',
      type: 'text',
      rows: 2,
      placeholder: 'Complete the information below to create a candidate account.',
    }),
    defineField({
      name: 'lastNameLabel',
      title: 'Last Name Label (Default)',
      type: 'string',
      initialValue: 'Họ',
      placeholder: 'Họ',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'lastNameLabelVi',
      title: 'Last Name Label VI',
      type: 'string',
      placeholder: 'Họ',
    }),
    defineField({
      name: 'lastNameLabelEn',
      title: 'Last Name Label EN',
      type: 'string',
      placeholder: 'Last Name',
    }),
    defineField({
      name: 'lastNamePlaceholder',
      title: 'Last Name Input Placeholder (Default)',
      type: 'string',
      initialValue: 'Nguyen',
      placeholder: 'Nguyen',
    }),
    defineField({
      name: 'lastNamePlaceholderVi',
      title: 'Last Name Input Placeholder VI',
      type: 'string',
      placeholder: 'Nguyen',
    }),
    defineField({
      name: 'lastNamePlaceholderEn',
      title: 'Last Name Input Placeholder EN',
      type: 'string',
      placeholder: 'Nguyen',
    }),
    defineField({
      name: 'firstNameLabel',
      title: 'First Name Label (Default)',
      type: 'string',
      initialValue: 'Tên',
      placeholder: 'Tên',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'firstNameLabelVi',
      title: 'First Name Label VI',
      type: 'string',
      placeholder: 'Tên',
    }),
    defineField({
      name: 'firstNameLabelEn',
      title: 'First Name Label EN',
      type: 'string',
      placeholder: 'First Name',
    }),
    defineField({
      name: 'firstNamePlaceholder',
      title: 'First Name Input Placeholder (Default)',
      type: 'string',
      initialValue: 'An',
      placeholder: 'An',
    }),
    defineField({
      name: 'firstNamePlaceholderVi',
      title: 'First Name Input Placeholder VI',
      type: 'string',
      placeholder: 'An',
    }),
    defineField({
      name: 'firstNamePlaceholderEn',
      title: 'First Name Input Placeholder EN',
      type: 'string',
      placeholder: 'An',
    }),
    defineField({
      name: 'emailLabel',
      title: 'Email Label (Default)',
      type: 'string',
      initialValue: 'Email',
      placeholder: 'Email',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'emailLabelVi',
      title: 'Email Label VI',
      type: 'string',
      placeholder: 'Email',
    }),
    defineField({
      name: 'emailLabelEn',
      title: 'Email Label EN',
      type: 'string',
      placeholder: 'Email',
    }),
    defineField({
      name: 'emailPlaceholder',
      title: 'Email Input Placeholder (Default)',
      type: 'string',
      initialValue: 'ten@example.com',
      placeholder: 'ten@example.com',
    }),
    defineField({
      name: 'emailPlaceholderVi',
      title: 'Email Input Placeholder VI',
      type: 'string',
      placeholder: 'ten@example.com',
    }),
    defineField({
      name: 'emailPlaceholderEn',
      title: 'Email Input Placeholder EN',
      type: 'string',
      placeholder: 'ten@example.com',
    }),
    defineField({
      name: 'phoneLabel',
      title: 'Phone Label (Default)',
      type: 'string',
      initialValue: 'Số điện thoại',
      placeholder: 'Số điện thoại',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'phoneLabelVi',
      title: 'Phone Label VI',
      type: 'string',
      placeholder: 'Số điện thoại',
    }),
    defineField({
      name: 'phoneLabelEn',
      title: 'Phone Label EN',
      type: 'string',
      placeholder: 'Phone number',
    }),
    defineField({
      name: 'phonePlaceholder',
      title: 'Phone Input Placeholder (Default)',
      type: 'string',
      initialValue: '0901234567',
      placeholder: '0901234567',
    }),
    defineField({
      name: 'phonePlaceholderVi',
      title: 'Phone Input Placeholder VI',
      type: 'string',
      placeholder: '0901234567',
    }),
    defineField({
      name: 'phonePlaceholderEn',
      title: 'Phone Input Placeholder EN',
      type: 'string',
      placeholder: '0901234567',
    }),
    defineField({
      name: 'passwordLabel',
      title: 'Password Label (Default)',
      type: 'string',
      initialValue: 'Mật khẩu',
      placeholder: 'Mật khẩu',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'passwordLabelVi',
      title: 'Password Label VI',
      type: 'string',
      placeholder: 'Mật khẩu',
    }),
    defineField({
      name: 'passwordLabelEn',
      title: 'Password Label EN',
      type: 'string',
      placeholder: 'Password',
    }),
    defineField({
      name: 'passwordPlaceholder',
      title: 'Password Input Placeholder (Default)',
      type: 'string',
      initialValue: 'Tối thiểu 6 ký tự',
      placeholder: 'Tối thiểu 6 ký tự',
    }),
    defineField({
      name: 'passwordPlaceholderVi',
      title: 'Password Input Placeholder VI',
      type: 'string',
      placeholder: 'Tối thiểu 6 ký tự',
    }),
    defineField({
      name: 'passwordPlaceholderEn',
      title: 'Password Input Placeholder EN',
      type: 'string',
      placeholder: 'Minimum 6 characters',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'description',
      media: 'image',
    },
  },
})
